---
- name: Install zulu yum repo
  yum:
    name: https://cdn.azul.com/zulu/bin/zulu-repo-1.0.0-1.noarch.rpm
    state: present

# RPM only supports major version
- name: install JDK via zulu yum
  yum:
    name: zulu{{ redhat_java_version }}
    update_cache: yes
