---
- name: split java_version into major/minor/patch components
  set_fact:
    split_version: "{{ java_version.split('.') }}"
- name: ensure java_major_version variable is set
  set_fact:
    java_major_version: "{{ split_version[0] }}"
- name: ensure java_zulu_version variable is set
  set_fact:
    java_zulu_version: "{{ split_version[2] | ternary('{{ split_version[0] }}.{{ split_version[1] }}+{{ split_version[2] }}', '{{ split_version[0] }}.{{ split_version[1] }}') }}"
